# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisUi2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Jarvis(object):
    def __init__(self):
        self.name = None
        self.logo = None
        self.centralwidget = None
        self.bg = None

    def setupUi(self, Jarvis):
        Jarvis.setObjectName("Jarvis")
        Jarvis.resize(1331, 720)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/jarvis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Jarvis.setWindowIcon(icon)
        Jarvis.setAutoFillBackground(False)
        Jarvis.setDocumentMode(False)
        Jarvis.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(Jarvis)
        self.centralwidget.setObjectName("centralwidget")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(80, 70, 511, 521))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("assets/jarvis.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(630, 110, 661, 451))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(150)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.bg = QtWidgets.QLabel(self.centralwidget)
        self.bg.setGeometry(QtCore.QRect(0, -20, 1341, 741))
        self.bg.setAutoFillBackground(False)
        self.bg.setStyleSheet("background: #ccffff;\n")
        self.bg.setText("")
        self.bg.setObjectName("bg")
        self.bg.raise_()
        self.logo.raise_()
        self.name.raise_()
        Jarvis.setCentralWidget(self.centralwidget)
        # Jarvis.showMaximized()
        self.retranslateUi(Jarvis)
        QtCore.QMetaObject.connectSlotsByName(Jarvis)

    def retranslateUi(self, Jarvis):
        _translate = QtCore.QCoreApplication.translate
        Jarvis.setWindowTitle(_translate("Jarvis", "Jarvis Voice Assistant"))
        self.name.setText(_translate("Jarvis", "Jarvis"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Jarvis = QtWidgets.QMainWindow()
    ui = Ui_Jarvis()
    ui.setupUi(Jarvis)
    Jarvis.show()
    sys.exit(app.exec_())
